version: "3.2"


services:
  api:
    container_name: api
    build: ./api
    environment:
      PG_CONNECTION_STRING: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@store:5432/${POSTGRES_DB}"
      PG_TEST_CONNECTION_STRING: postgres://example:example@testing_store:5432/test
      PORT:
      BUILD_ENV:
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./api/src:/usr/app/api/src


  db:
    container_name: store   
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      POSTGRES_DB: 
      POSTGRES_HOST_AUTH_METHOD: 
    ports:
      - 5432:5432
    volumes:
      - ./_volumes:/var/lib/postgresql/data


  testing_db:
    container_name: testing_store   
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      POSTGRES_DB: 
      POSTGRES_HOST_AUTH_METHOD: 
    ports:
      - 5433:5432